#!/usr/bin/env php
<?php
//if (getenv('APP_ENV') != 'prod') {
//    die("I'm not going to run any deployment procedure as we're not in production.\n");
//}

echo `./artisan migrate`;
echo `./artisan route:cache`;
echo `./artisan config:cache`;
echo `node_modules/.bin/gulp --production`;
