#!/usr/bin/env php
<?php
if (getenv('APP_ENV') != 'prod') {
    die("Skipping post-deploy procedures as we're not in production.\n");
}

echo `./artisan migrate`;
//As build and runtime paths are different on Heroku, there's a command on Composer (set-cache) that is run at boot, instead
//echo `./artisan route:cache && ./artisan config:cache`;
echo `DISABLE_NOTIFIER=true node_modules/.bin/gulp --production`;
