#!/usr/bin/env php
<?php
// This file must be PHP5 friendly!!
$container = getenv('CONTAINER');
if (!$container) {
    $command = 'help';
} else {
    $command = isset($argv[1])? $argv[1] : 'start';
}

//echo "Container set: $container\n";

switch ($command) {
    case 'help':
    case '--help':
    case '-h':
        echo <<<'HELP'
== Docker helper script ==

First of all:
    You need a $CONTAINER environment variable set so we know the container's name :)
    You can create it by issuing "export CONTAINER=trusting_einstein"

List of available commands:
    help        this thing you're seeing right now
    start       [default] starts up the given $CONTAINER
    psql        opens up the psql prompt with the right user
    bash/shell  opens up the shell prompt
    artisan/art runs an Artisan command (i.e. ./dock art migrate --force)
    ***         other commands will simply run in Artisan (i.e. ./dock migrate --force)

HELP;
        die;

    case 'psql':
        $cmd = 'exec -it';
        $run = 'psql -h 127.0.0.1 -WU konato konato';
        break;

    case 'bash':
    case 'shell':
        $cmd = 'exec -it';
        $run = 'bash';
        break;

    default:
        $artisan = join(' ', array_splice($argv, 1));
    case 'art':
    case 'artisan':
        $artisan = isset($artisan)? $artisan : join(' ', array_splice($argv, 2));
        $cmd = 'exec';
        $run = './artisan '.$artisan;
        break;

    case 'start':
        $cmd = 'start';
        $run = '';
}

$cmd = "docker $cmd $container $run";
echo "> $cmd\n";
passthru($cmd);
